### PR TITLE
Add support for very large integers represented by string

### PR DESCRIPTION
**Pull request by zhongliwu**
1. Support String parse for very large integer.
2. Support a return val for illegal input string in decode functions.

### CODE REVIEW

**Comment by zhongliwu** [comment]
The test case I used:
For encode:
int testNum1 = 0;
int testNum2 = 50;
int testNum3 = 10000000;
int testNum4 = -50;
int testNum5 = 256;

For decode:
String testStr1 = "";
String testStr1 = "ad";
String testStr1 = "ghj";
String testStr1 = "b";
String testStr1 = "3-";

**Comment by ocram** [comment]
@zhongliwu Thank you very much!

Great to have a `BigInteger` solution here :)

Not sure if we should merge. In the current form, we cannot merge, anyway, because it contains too many unrelated changes:
- visibility of class members reduced
- return value of `-1` in case of an error
- checking for errors using new `FORBIDSET`

Apart from that, the parameter of `encode(...)` should be a `BigInteger` and the return value of `decodeWithBigNumber(...)` as well, shouldn't they?

Anyway, we'll definitely leave this here so that anybody who needs `BigInteger` support can use the code from your pull request here :)

**Comment by zhongliwu** [comment]
@mwaclawek Thanks for kind reply! Can I ask several questions related with your issue?
1. So the class members like FORBIDSET should be set as private, right?
2. How to we handle errors if the input is not valid? e.g. the input of encode() is not a valid number

In the same time, just want to let you know I set the return type of decodeWithBigNumber(...) as a string because I think it might make this function more easy to use. But if you think BigInteger is better, I will change it BigInteger.

Anyway, thanks for pay attention of my pull request as this is my first contribution on a open source project :)

**Comment by ocram** [comment]
@zhongliwu Congratulations then, you created a really good first pull request! :)

The things we didn't like about it are mostly subjective, as you could see.

There are just a few things that we'll try to explain in a better form again:
- You don't need the separate `FORBIDSET`. Just look at the [documentation](http://developer.android.com/reference/java/lang/String.html#indexOf%28int%29) for the `indexOf(...)` method: You can just check if it returns `-1` for `ALPHABET`. You see? No need for more class members and variables.
- Reducing the visibility of `ALPHABET` and `BASE` was definitely the right thing to do. We'd just prefer if this was a separate pull request because it's not related.
- Returning `-1` in case of an error is not compatible to the way the library worked so far. But it may be better.
- The parameter of `encode(...)` should be a `BigInteger` and the return value of `decodeWithBigNumber(...)` as well. Do you agree?

**Comment by zhongliwu** [comment]
@mwaclawek Thanks for feed back!

I just adjusted my code responsive to your comments here. Just created a pull request to let you review the code there. But I just don't know how to do with the 'return -1 in case of error' problem.

I also add the JavaScript code for the BigInteger version.

Let me know if you have any questions.

**Pull request closed without merging**
